name: iguana_taman_wisata
description: "A new Flutter project for managing a tourist park."

# This prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+5
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.0.15

  # Cupertino Icons for iOS style icons.
  cupertino_icons: ^1.0.6

  # HTTP package for making network requests.
  http: ^1.2.1

  # Provider for state management.
  provider: ^6.0.5

  # Cached network image for handling images from the internet.
  cached_network_image: ^3.2.1

  # Flutter Lints for recommended linting rules.
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter specific settings.
flutter:
  uses-material-design: true

  # Add assets like images or fonts here.
  assets:
    - assets/images/emergency.png
    - assets/images/damkar.png
    - assets/images/ambulance.png
    - assets/images/polisi.png
    - assets/images/call.png
    - assets/images/siralaps.png

  # Custom fonts can be added here if needed.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
